### PR TITLE
Update previewer using latest response code

### PR DESCRIPTION
**Pull request by junkaiman**
### Summary
As titled

### Screenshot
https://github.com/user-attachments/assets/2a39280e-8088-40d4-9945-47dd9f0aacce

### Checklist
- [x] My code follows ESLint rules and passes all tests.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lpplake** [comment]
💯💯💯

**Comment by SabrinaKung** [comment]
Awesome!
Would the code section in previewer be formatted?

**Review by lpplake — APPROVED** [review]
LGTM! Nice work!

**Comment by junkaiman** [comment]
> Awesome! Would the code section in previewer be formatted?

Yes. The code in the previewer section will be formatted but not for the one in the chat. @ZhuoyangM will fix that.

**Pull request merged**
